version: '3'
services:
  minio:
    container_name: minio
    image: bitnami/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: 123456a@
    volumes:
      - ./storage/minio:/minio
    command: server /data
    networks:
      - minio
    depends_on:
      - db
networks:
  minio:
    driver: bridge
volumes:
  minio:
